#!/bin/sh
# NOTE: Process accounting will use up a considerable amount of disk space
NAME="Process Accounting"

main() {
    touch /var/log/account/pacct
    accton /var/log/account/pacct
}

stop() {
    accton off
}

. /etc/leaninit/rc.svc
