#!/bin/sh
NAME="Apache Web Server"

main()
{
	mkdir -p /run/httpd /var/run/httpd
	fork httpd -k start -DFOREGROUND
}

stop()
{
	httpd -k graceful-stop
}

reload()
{
	kill -HUP $__svcpid
}

. /etc/leaninit/rc.svc
