#!/bin/sh
NAME="ClamAV"
__svcname=$(basename "$0")

main() {
    mkdir -p /run/clamav
    chown clamav:root /run/clamav
    clamd || return 1
    ln -sf /run/clamav/clamd.pid "$__svcpidfile"
    waitfor networking optional && freshclam
}

. /etc/leaninit/rc.svc
