#!/bin/sh
#DEF BSD
. /etc/leaninit/rc.conf.d/ntpd.conf
#ENDEF
NAME="ntpd"

main() {
    waitfor networking
#DEF BSD
    [ "$NTPDATE" = "true" ] && ntpdate $(grep 'server' /etc/ntp.conf | grep -v '#' | awk '{ print $2 }')
#ENDEF
    ntpd -p "$__svcpidfile"
}

. /etc/leaninit/rc.svc
