#!/bin/sh
. /etc/leaninit/rc.conf.d/ntp.conf
NAME="ntpd"

main()
{
    waitfor networking
#DEF NetBSD
    if [ "$NTPDATE" = "true" ]; then
        ntpdate $(grep 'server' /etc/ntp.conf | grep -v '#' | awk '{ print $2 }')
    fi
#ENDEF
    ntpd -p "$__svcpidfile"
}

. /etc/leaninit/rc.svc
