#!/bin/sh
NAME="LeanInit Settings"

main()
{
#DEF Linux
	# Set up network interfaces
	ip link set up dev lo &
	if [ -n "$NETFACE" ]; then
		for n in $NETFACE; do
			print "Setting up $n for networking..." log "$BLUE" "$WHITE"
			ip link set up dev "$n" &
		done
	fi

	# Keyboard layout
	print "Setting the keyboard layout to $KEYMAP..." log "$BLUE" "$WHITE"
	loadkeys "$KEYMAP"

	# Console font
	if [ -n "$CONSOLEFONT" ]; then
		print "Setting the console font to $CONSOLEFONT" log "$BLUE" "WHITE"
		setfont "$CONSOLEFONT"
	fi
#ENDEF
	# Universal settings
	hostname "$HOSTNAME" &
	ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime &
	wait
}

. /etc/leaninit/rc.svc
