#!/bin/sh
NAME="LeanInit Settings"

main()
{
	# Set the machine's hostname
	if [ -n "$HOSTNAME" ]; then
		hostname "$HOSTNAME"
	fi

	# Set the timezone
	if [ -n "$TIMEZONE" ]; then
		rm -f /etc/localtime
		ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
	fi
#DEF Linux

	# Set the keyboard layout
	print "Setting the keyboard layout to $KEYMAP..." log "$BLUE" "$WHITE"
	loadkeys "$KEYMAP"

	# Set the console font
	if [ -n "$CONSOLEFONT" ]; then
		print "Setting the console font to $CONSOLEFONT" log "$BLUE" "WHITE"
		setfont "$CONSOLEFONT"
	fi
#ENDEF
}

. /etc/leaninit/rc.svc
