#!/bin/sh
NAME="LeanInit Settings"
__svcname=$(basename "$0")

main() {
    # Set the machine's hostname
    [ "$HOSTNAME" ] && hostname "$HOSTNAME"

    # Set the timezone
    if [ "$TIMEZONE" ]; then
        rm -f /etc/localtime
        ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
    fi

#DEF FreeBSD
    # Set the keyboard layout
    println "Setting the keyboard layout to $KEYMAP..." log "$BLUE" "$WHITE"
    kbdcontrol -l "$KEYMAP"
#ENDEF
#DEF NetBSD
    # Load wscons from rc.d
    /etc/rc.d/wscons start
#ENDEF
#DEF Linux
    # Set the keyboard layout
    println "Setting the keyboard layout to $KEYMAP..." log "$BLUE" "$WHITE"
    loadkeys "$KEYMAP"

    # Set the console font
    if [ "$CONSOLEFONT" ]; then
        println "Setting the console font to $CONSOLEFONT" log "$BLUE" "$WHITE"
        setfont "$CONSOLEFONT"
    fi
#ENDEF
}

. /etc/leaninit/rc.svc
