#!/bin/sh
NAME="Swapfile"
__svcname=$(basename "$0")

main() {
    if [ ! -f /swapfile ]; then
        println 'Please create a swapfile at /swapfile!' "$RED"
        __fail 1
    fi

    swapon /swapfile
}

stop() {
    swapoff /swapfile
}

. /etc/leaninit/rc.svc
