#!/bin/sh
NAME="swap"
MSG="Turning on all swap partitions"
__svcname=$(basename "$0")

main() {
#DEF FreeBSD
    swapon -aL
#ENDEF
#DEF NetBSD
    swapon -a
#ENDEF
#DEF Linux
    swapon -a
#ENDEF
}

#DEF FreeBSD
stop() {
    swapoff -aL
}
#ENDEF
#DEF Linux
stop() {
    swapoff -a
}
#ENDEF

. /etc/leaninit/rc.svc
