#!/bin/sh
NAME="Swapfile"

main()
{
    if [ ! -f /swapfile ]; then
        print 'Please create a swapfile at /swapfile!' "$RED"
        __fail 1
    fi

    swapon /swapfile
}

stop()
{
    swapoff /swapfile
}

. /etc/leaninit/rc.svc
