#!/bin/sh
NAME="swap"
MSG="Turning on all swap partitions"

main()
{
#DEF FreeBSD
    swapon -aL
#ENDEF
#DEF NetBSD
    swapon -a
#ENDEF
#DEF Linux
    swapon -a
#ENDEF
}

stop()
{
#DEF FreeBSD
    swapoff -aL
#ENDEF
#DEF NetBSD
    swapoff -a
#ENDEF
#DEF Linux
    swapoff -a
#ENDEF
}

. /etc/leaninit/rc.svc
