#!/bin/sh
NAME="sysctl"

main()
{
#DEF Linux
    # Use util-linux sysctl if it is available
    if sysctl --system 2> /dev/null; then
        return 0
    fi

    # BusyBox sysctl
    if [ -d /usr/lib/sysctl.d ] && [ "$(ls /usr/lib/sysctl.d)" ]; then
        SYSCTLD="$(echo /usr/lib/sysctl.d/*)"
    fi
    for s in /etc/sysctl.conf /etc/sysctl.conf.local $SYSCTLD; do
        sysctl -p /etc/sysctl.conf >> "$__svclog"
    done
#ENDEF
#DEF NetBSD
    for s in /etc/sysctl.conf /etc/sysctl.conf.local; do
        sysctl -f /etc/sysctl.conf >> "$__svclog"
    done
#ENDEF
#DEF FreeBSD
    for s in /etc/sysctl.conf /etc/sysctl.conf.local; do
        sysctl -f /etc/sysctl.conf >> "$__svclog"
    done

    # If devd is disabled, disable devctl in the kernel
    if ! checkfor service devd; then
        sysctl hw.bus.devctl_queue=0
    fi
#ENDEF
}

. /etc/leaninit/rc.svc
