#!/bin/sh
NAME="sysctl"

main()
{
	for s in /etc/sysctl.conf /etc/sysctl.conf.local; do
		if [ -e $s ]; then
#DEF FreeBSD
			sysctl -f /etc/sysctl.conf >> "$__svclog"
#ENDEF
#DEF Linux
			sysctl -p /etc/sysctl.conf >> "$__svclog"
#ENDEF
		fi
	done
#DEF FreeBSD

	# If devd is disabled, disable devctl in the kernel
	if ! checkfor service devd; then
		sysctl hw.bus.devctl_queue=0
	fi
#ENDEF
}

. /etc/leaninit/rc.svc
