#!/bin/sh
NAME="sysctl"

main()
{
#DEF Linux
	if [ -d /usr/lib/sysctl.d ] && [ -n "$(ls /usr/lib/sysctl.d)" ]; then
         SYSCTLD="$(echo /usr/lib/sysctl.d/*)"
	fi
	for s in /etc/sysctl.conf /etc/sysctl.conf.local $SYSCTLD; do
		if [ -e "$s" ]; then
			sysctl -p /etc/sysctl.conf >> "$__svclog"
#ENDEF
#DEF FreeBSD
	for s in /etc/sysctl.conf /etc/sysctl.conf.local; do
		if [ -e "$s" ]; then
			sysctl -f /etc/sysctl.conf >> "$__svclog"
#ENDEF
		fi
	done
#DEF FreeBSD

	# If devd is disabled, disable devctl in the kernel
	if ! checkfor service devd; then
		sysctl hw.bus.devctl_queue=0
	fi
#ENDEF
}

. /etc/leaninit/rc.svc
