#!/bin/sh

# Service for X Server Display Managers
. /etc/leaninit/rc.conf.d/xdm.conf
NAME="$XDMNAME"
TYPE="display-manager"

# The main function
main()
{
	if [ -z "$DM" ] || [ ! -x "$(command -v $DM)" ]; then
		print 'The xdm service failed to start due to $DM being invalid!' log "$RED"
		return 1
	fi

	# Dependencies of the X Server
#DEF Linux
	waitfor udev
#ENDEF
	waitfor service dbus
	waitfor login-daemon optional
	install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix # Required for GDM to function

	# Launch the display manager and symlink the PID file if it is valid
	fork "$XDM"
	if [ -r "$XDMPID" ]; then
		ln -sf "$XDMPID" "$__svcpidfile"
	fi
}

# Kill the X server manually
stop()
{
	pkill -x "$DM"
	pkill -x Xorg
}

. /etc/leaninit/rc.svc
