#!/bin/sh

# Service for X Server Display Managers
#DEF FreeBSD
. /etc/leaninit/rc.conf.d/xdm.conf
NAME="$XDMNAME"
#ENDEF
#DEF NetBSD
NAME="X Display Manager"
XDM="/usr/X11R7/bin/xdm"
#ENDEF
#DEF Linux
. /etc/leaninit/rc.conf.d/xdm.conf
NAME="$XDMNAME"
#ENDEF
TYPE="display-manager"

# The main function
main()
{
    if [ ! "$XDM" ] || [ ! -x "$(command -v $XDM)" ]; then
        print 'The xdm service failed to start due to $XDM being invalid!' log "$RED"
        return 1
    fi

    # Dependencies of the X Server
    waitfor service dbus optional
#DEF NetBSD
    waitfor service settings
#ENDEF
#DEF Linux
    checkfor service udev
    waitfor login-daemon optional
#ENDEF
    install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix # Required for GDM to function

    # Launch the display manager and symlink the PID file if it is valid
    fork "$XDM"
#DEF FreeBSD
    if [ "$XDMPID" ]; then
        waitfor file "$XDMPID" optional
        ln -sf "$XDMPID" "$__svcpidfile"
    fi
#ENDEF
#DEF Linux
    if [ "$XDMPID" ]; then
        waitfor file "$XDMPID" optional
        ln -sf "$XDMPID" "$__svcpidfile"
    fi
#ENDEF
}

# Kill the X server manually
stop()
{
    pkill -x "$XDM"
    pkill -x Xorg
}

. /etc/leaninit/rc.svc
