#!/bin/sh

# Service for X Server Display Managers
. /etc/leaninit/rc.conf.d/xdm.conf
. /etc/leaninit/rc.conf # This line is kept for backward compatibility. It will be removed in a later major update.
NAME="$XDMNAME"
TYPE="display-manager"

# The main function
main() {
	if [ -z "$DM" ] || [ ! -x "$(command -v $DM)" ]; then
		print 'The xdm service failed to start due to $DM being invalid!' log "$RED"
		return 1
	fi
	waitfor service dbus
	waitfor login-daemon optional
	install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix # Required for GDM to function
	fork "$DM"
}

# Kill the X server manually
stop() {
	pkill -x Xorg
}

. /etc/leaninit/rc.svc
