#!/bin/sh
NAME="ZFS"
MSG="Mounting ZFS file systems"

# Mount ZFS file systems
main()
{
#DEF BSD
    # This for loop is for compatibility with beadm(1)
    for z in $(df -PT | sed 's:/: :g' | awk '/ zfs /{ print $1 }'); do
        zfs mount "$z"
    done 2> /dev/null
#ENDEF

    # mount -a equivalent (includes NFS)
    zfs mount -a
    zfs share -a
}

# Unmount ZFS file systems when this service stops
stop()
{
    zfs unmount -a
    zfs unshare -a
}

. /etc/leaninit/rc.svc
