#!/bin/sh
NAME="ZFS"
MSG="Mounting ZFS file systems"

# Mount ZFS file systems
main()
{
#DEF Linux
	# Wait for kernel modules to be loaded (to ensure ZFS is active)
	waitfor service kmod

#ENDEF
	# This is done in a for loop for compatibility with beadm(1)
	for z in $(df -t zfs | tail -n +2 | awk '{print $1}'); do
		zfs mount "$z"
	done

	# mount -a equivalent (includes NFS)
	zfs mount -a
	zfs share -a

	# Make ZFS datasets read-write (used in case root (/) is a read-only ZFS dataset)
	for z in $(zpool list -Ho name); do
		print "Turning readonly off for dataset $z..." nolog "$PURPLE" "$WHITE"
		zfs readonly=off "$z"
	done
}

# Unmount ZFS file systems when this service stops
stop()
{
	zfs unmount -a
	zfs unshare -a
}

. /etc/leaninit/rc.svc
