#!/bin/sh
NAME="ZFS"
MSG="Mounting ZFS file systems"

# Mount ZFS file systems
main()
{
#DEF BSD
    # This for loop is for compatibility with beadm(1)
    for z in $(df -PT 2> /dev/null | awk '/ zfs /{ print $1 }'); do
        zfs mount "$z"
    done
#ENDEF

    # mount -a equivalent (includes NFS)
    zfs mount -a
    zfs share -a

    # Make ZFS datasets read-write (used in case root (/) is a read-only ZFS dataset)
    for z in $(zpool list -Ho name); do
        print "Turning readonly off for dataset $z..." nolog "$PURPLE" "$WHITE"
        zfs readonly=off "$z"
    done
}

# Unmount ZFS file systems when this service stops
stop()
{
    zfs unmount -a
    zfs unshare -a
}

. /etc/leaninit/rc.svc
