.\" Copyright © 2018-2020 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd April 17, 2020
.Dt RC.CONF 5
.Os
.Sh NAME
.Nm rc.conf
.Nd config file for
.Nm rc(8)
.Sh DESCRIPTION
.Em /etc/leaninit/rc.conf
allows you to configure various settings, such as your hostname.
This file is used by the
.Nm leaninit-rc.svc(8)
script.
.Sh OPTIONS
.Em /etc/leaninit/rc.conf
allows you to change the following settings:

.Em HOSTNAME :
Changes the hostname using
.Nm hostname(1) .
Commented out by default.

.Em TIMEZONE :
Changes the timezone by forcefully making a symlink. Commented out by default.

#DEF Linux
.Em KEYMAP :
Changes the keyboard layout. Commented out by default.

.Em CONSOLEFONT :
Changes the console font on the ttys (Linux only). Commented out by default.
#ENDEF

#DEF FreeBSD
.Em KEYMAP :
Changes the keyboard layout. Commented out by default.

.Em WIRED :
Sets the networking interface(s) to use with the wpa_supplicant wired driver.
Set to eth0 by default.

.Em WIRELESS :
Sets the networking interface(s) to use with the wpa_supplicant bsd driver.
Set to wlan0 by default.

.Em NDIS :
Sets the networking interface(s) to use with the wpa_supplicant ndis driver.
#ENDEF

#DEF NetBSD
.Em WIRED :
Sets the networking interface(s) to use with the wpa_supplicant wired driver.
Set to we0 by default.

.Em WIRELESS :
Sets the networking interface(s) to use with the wpa_supplicant bsd driver.
Set to wlan0 by default.
#ENDEF

.Em DELAY :
Have
.Nm rc
wait for all services and
.Nm rc.local
scripts to exit before having
.Nm rc
itself exit.
This will prevent LeanInit from launching any getty from
.Nm ttys(5)
if a service or
.Nm rc.local
script fails to exit.
This setting should only be used for debugging.
.Sh ADDITIONAL OPTIONS
The following settings can be set in config files located in
.Em /etc/leaninit/rc.conf.d :

#DEF FreeBSD
#DEF NetBSD
.Em NTPDATE :
When this is set to true, the ntpd service will run ntpdate(8) during boot to update the system's clock.
#ENDEF

.Em XDM
(xdm.conf):
Sets the path to the executable of the Display Manager used by the xdm service.

.Em XDMNAME
(xdm.conf):
Sets the name of the Display Manager used by the xdm service.

.Em XDMPID
(xdm.conf):
Sets the path to the Display Manager's PID file for use by the xdm service (this setting is optional).

#DEF Linux
.Em FASTLOGIN
(xdm.conf):
If this is set to true, xdm will start in aggressive parallel alongside udev,
which will temporarily disable the system's power button until the user logs in.
As this feature does have a negative effect, it is disabled by default.

.Em DEVEXEC
(udev.conf):
Sets the location of either
.Nm udev(7)
or
.Nm mdev .
Set to
.Em /sbin/udevd
for udev by default.

.Em CRON
(cron.conf)
Sets the executable name in
.Em $PATH
or the absolute path to the executable for
.Nm cron(8) .

.Em CRONFLAGS
(cron.conf)
Sets the flags
.Nm cron
will be run with.
.Nm Cron
must be set to run in the foreground or else the cron service will fail.
#ENDEF
.Sh SEE ALSO
leaninit-rc(8), leaninit-rc.svc(8), leaninit-ttys(5), halt(8)
.Sh AUTHOR
Johnothan King
