#!/bin/sh
NAME="WPA Supplicant"
TYPE="networking"

# Run wpa_supplicant on all interfaces
restart()
{
	if [ -n "$WIRED" ]; then
		for n in $WIRED; do
			fork wpa_supplicant -s -Dwired "-i$n" -c/etc/wpa_supplicant.conf
		done
	fi
	if [ -n "$WIRELESS" ]; then
		for n in $WIRELESS; do
			fork wpa_supplicant -s -Dbsd "-i$n" -c/etc/wpa_supplicant.conf
		done
	fi
	if [ -n "$NDIS" ]; then
		for n in $NDIS; do
			fork wpa_supplicant -s -Dndis "-i$n" -c/etc/wpa_supplicant.conf
		done
	fi
}

# The main function
main()
{
	waitfor process wpa_supplicant
	sleep 0.5
	pkill -KILL -x wpa_supplicant
	restart  # Run wpa_supplicant
}

. /etc/leaninit/rc.svc
