#!/bin/sh

# Service for X Server Display Managers
. /etc/leaninit/rc.conf.d/xdm.conf
NAME="$XDMNAME"
TYPE="display-manager"

# The main function
main() {
    if [ ! "$XDM" ] || [ ! -x "$(command -v $XDM)" ]; then
        println 'The xdm service failed to start due to $XDM being invalid!' log "$RED"
        return 1
    fi

    # Dependencies of the X Server
    waitfor service dbus
    waitfor service settings

    # Required for GDM to function
    install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix

    # Launch the display manager and symlink the PID file if it is valid
    fork "$XDM"
    if [ "$XDMPID" ]; then
        waitfor file "$XDMPID" optional
        ln -sf "$XDMPID" "$__svcpidfile"
    fi
}

# Kill the X server manually
stop() {
    rm -f /var/run/leaninit/xdm* "/var/run/leaninit/$TYPE.type"
    pkill -x "$XDM"
    pkill -x Xorg
}

. /etc/leaninit/rc.svc
