#!/bin/sh

# Launch getties
NAME="LGetty"
TYPE=getty

# Open getties on the ttys specified in /etc/leaninit/ttys
main() {
    for tty in $(grep -v '#' /etc/leaninit/ttys); do
        fork lgetty "/dev/$tty"
    done
}

. /etc/leaninit/rc.svc
