#!/bin/sh
#
# Copyright (c) 2017 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# halt(8)
#

# Determine what to do
case "$1" in

     # Halt and Poweroff both go to runlevel zero
    "")
        export RUNLEVEL=0 ;;

     # Ignored
    "-p")
        export RUNLEVEL=0 ;;

    # Reboot
    "-r")
        export RUNLEVEL=6 ;;

    # Other arguments are invalid
    *)
        echo "Usage: $0 [-pr]"
        echo ""
        echo "  -r            Restart the system"
        echo "  -p            Ignored for compatibility"
        exit 1 ;;
esac

# Unmount, or mount as read only, all filesystems
umount -rat nodebugfs,nodevfs,noprocfs,nosysfs,notmpfs
mount -fo remount,ro /

# Send the new runlevel to init
exec init $RUNLEVEL
