#!/bin/sh
#
# Copyright (c) 2017 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

usage()
{
	echo $1
	echo ""
	echo "Usage: lsvc [-de] service level"
	echo ""
	echo "  -d            Disable a service"
	echo "  -e            Enable a service"
	exit $2
}

if [ "$2" = "" ] || [ "$3" = "" ]; then
	usage 'This program requires three arguments!' 1
fi

enable()
{
	if [ ! -e /etc/leaninit/$3 ]; then
		usage "The level $3 does not exist!" 1
	elif [ ! -e /etc/leaninit/svc/$2 ]; then
		usage "The service $2 doesn't exist!" 1
	elif [ -L /etc/leaninit/$3/$2 ]; then
		echo "The service $2 is already enabled in level $3"
		exit 0
	fi

	ln -s /etc/leaninit/svc/$2 /etc/leaninit/$3
	echo "The service $2 has been enabled in level $3"
	exit 0
}

disable()
{
	if [ ! -e /etc/leaninit/$3 ]; then
		usage "The level $3 does not exist!" 1
	elif [ ! -L /etc/leaninit/$3/$2 ]; then
		if [ -e /etc/leaninit/svc/$2 ]; then
			echo "The service $2 is not enabled in level $3"
			exit 0
		else
			usage "The service $2 doesn't exist!" 1
		fi
	fi

	rm /etc/leaninit/$3/$2
	echo "The service $2 has been disabled in level $3"
	exit 0
}

case "$1" in
	-e)
		enable ;;
	-d)
		disable ;;
	*)
		usage "Argument $1 is invalid!" 1 ;;
esac
