#!/bin/sh
#
# Copyright (c) 2017 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Load /etc/profile
. /etc/profile

# Fork function
fork() {
	setsid "$@" &
}

# Turn off echo if quiet boot is used, and turn it on if verbose boot is used.
if [ "$1" = "v" ]; then
	export OUT="/dev/stdout"
	print() {
		echo "$@"
		echo "$@" >> /var/log/leaninit.log
	}
else
	export OUT="/dev/null"
	print() {
		echo "$@" >> /var/log/leaninit.log
	}
fi

# Echo to the console (if using verbose boot)
print "LeanInit running on $(uname -srm)"

# Remount / as read-write
mount -o remount,rw /

# Set up the drives and partitions as according to /etc/fstab
mount -a
fork swapon -a

# Load all sysctl settings
fork sysctl -a > $OUT

# Set the hostname
if [ -e /etc/hostname ] && [ "$(cat /etc/hostname)" != "" ]; then
	print "Setting the hostname to $(cat /etc/hostname)..."
	fork hostname $(cat /etc/hostname)
fi

# Set a keyboard layout, if needed (depends on kbd)
if [ -e /etc/leaninit/kbd.conf ] && [ "$(cat /etc/leaninit/kbd.conf)" != "" ]; then
	print "Setting the keyboard layout to $(cat /etc/leaninit/kbd.conf)..."
	fork loadkeys $(cat /etc/leaninit/kbd.conf)
fi

# Load services
for i in `ls /etc/leaninit/svce`; do
	. /etc/leaninit/svc/${i}
	print "Starting ${NAME}..."
	run
	echo "Started ${NAME}" >> /var/log/v7init.log
done

# Open some gettys, reserving tty7 for the X server and Wayland
print "Launching gettys..."
for i in `cat /etc/ttys`; do
	fork agetty 38400 $i
done

# Launch agetty
agetty 38400 tty1
