#!/bin/sh
#
# Copyright (c) 2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# svc-run - used internally by rc and lsvc to start services
#

# Only allow root to run this, with proper arguments
if [ `id -u` != 0 ] || [ "$2" = "" ]; then
	echo "This script is only meant for internal use!"
	exit 1
fi

# Source /etc/leaninit/rc.api
. /etc/leaninit/rc.api

# Start the service
. /etc/leaninit/svce/$1
export $NAME
$2 "Starting $NAME..."

if [ $2 = print ]; then
	main > $OUT
else
	main
fi

# Return output
RET=$?
if [ $? = 0 ]; then
	$2 "Started $NAME successfully"
else
	$2 "WARNING: $NAME failed to start (exited with status $RET)"
fi
