#!/bin/sh

# Service for nvidia-persistenced
NAME="nvidia-persistenced"
TARGET=Linux

main() {
    nvidia-persistenced
    ln -sf /var/run/nvidia-persistenced/nvidia-persistenced.pid "$__svcpidfile"
}

. /etc/leaninit/rc.svc
