#!/bin/sh
NAME="Kernel Modules"
MSG="Loading kernel modules"

main()
{
	if [ -d /etc/modules-load.d ] && [ -n "$(ls /etc/modules-load.d)" ]; then
		modprobe -a $(kmod static-nodes | awk '/Module:/ {print $2}') $(cat /etc/modules-load.d/* | grep -v '#')
	else
		modprobe -a $(kmod static-nodes | awk '/Module:/ {print $2}')
	fi
}

. /etc/leaninit/rc.svc
