.\" Copyright (c) 2018 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd August 2, 2018
.Dt INIT 8
.Os
.Sh NAME
.Nm leaninit
.Nd a fast init system
.Sh SYNOPSIS
.Nm init
.Oo
.Nm 0 | 6
.Sh DESCRIPTION
LeanInit is a Research Unix/BSD-style init system developed for Linux and FreeBSD operating systems.
When LeanInit is executed, it will first check if it is running as
.Nm PID
1.
.Pp
If it is
.Nm PID
1, LeanInit will run
.Nm login_tty(3)
to open the initial tty,
.Em /dev/tty1
on Linux and
.Em /dev/ttyv0
on FreeBSD. It will then output basic system information
to the initial tty and run
.Nm rc(8)
as a child process. After
.Nm rc(8)
is executed, LeanInit will suspend its own execution until it receives a signal.
.Pp
If it is not
.Nm PID
1, however, LeanInit will instead read from argv to emulate a few System V-like options.
The following options available are:
.Pp
.Nm 0
Power-off

.Nm 6
Reboot
.Pp
.Sh FILES
.Em /etc/leaninit.d/rc
Primary init script run by LeanInit

.Em /etc/rc
Secondary init script that is run if
.Em /etc/leaninit.d/rc
does not exist.

.Em /etc/leaninit.d/rc.conf
Provides config settings for
.Nm rc(8)
and LeanInit scripts

.Em /etc/leaninit.d/rc.api
Provides variables and functions for LeanInit scripts

.Em /etc/leaninit.d/svc.d
Folder containing scripts for starting various extra services (such as D-BUS)

.Em /etc/leaninit.d/svc.e
Location of svc files created for services enabled by
.Nm lsvc(8).

.Em /etc/leaninit.d/svc-start
Internal script which starts services

.Em /etc/leaninit.d/svc-stop
Internal script which stops services

.Em /var/log/leaninit/leaninit.log
Default log file for LeanInit

.Em /var/log/leaninit/leaninit.log.old
Log file from the previous instance of LeanInit
.Sh SEE ALSO
lsvc(8), halt(8), rc(8), rc.conf(5), rc.api(8), lttys(5), svc-start(8), svc-stop(8)
.Sh AUTHOR
Johnothan King
