.\" Copyright © 2020 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd March 13, 2020
.Dt RC.BANNER 8
.Os
.Sh NAME
.Nm rc.banner
.Nd shows a quick banner(1) or neofetch(1) at system startup
.Sh DESCRIPTION
The
.Nm rc.banner
script will run before rc(8) at system startup if the banner argument is passed to LeanInit by a bootloader,
with the intended use being to run a program such as banner.
This is not the same as the standard splash argument, as it will not trigger plymouth.
.Sh SEE ALSO
leaninit(8), leaninit-rc(8), banner(1), screenfetch(1), neofetch(1)
.Sh AUTHOR
Johnothan King
