.\" Copyright (c) 2018 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd August 17, 2018
.Dt INIT 8
.Os
.Sh NAME
.Nm leaninit
.Nd a fast init system
.Sh SYNOPSIS
.Nm init
.Oo
.Nm 0 | 6
.Sh DESCRIPTION
.Nm LeanInit
is a BSD-style init system that is developed for Linux and FreeBSD.
When
.Nm LeanInit
is executed, it will detect if it is running as
.Nm PID
1.
.Pp
If it is
.Nm PID
1,
.Nm LeanInit
will run
.Nm login_tty(3)
to open the initial tty,
.Em /dev/tty1
on Linux and
.Em /dev/ttyv0
on FreeBSD. It will then output basic system information
to the initial tty and run
.Nm lrc(8)
as a child process. After
.Nm lrc(8)
is executed,
.Nm LeanInit
will suspend its own execution until it receives a signal.
.Pp
If it is not
.Nm PID
1,
.Nm LeanInit
will instead emulate the following System V runlevels:
.Pp
.Nm 0
Poweroff

.Nm 6
Reboot

Passing -s to
.Nm LeanInit
before booting will cause it to start the
system in single user mode. Switching to single user mode by running 'init 1'
is currently not possible.

.Nm LeanInit
outputs text with the following color coding:

.Nm Cyan star and White text:
A message from the
.Nm LeanInit
binary

.Nm Purple star and White text:
A generic message that is not logged

.Nm Blue star and White text:
A generic message that is logged

.Nm Green star and White text:
A message that indicates a successful action

.Nm Purple star and Yellow text:
A warning message

.Nm Red star and Red text:
An error message
.Pp
.Sh FILES
.Em /etc/leaninit.d/rc
Primary init script run by
.Nm LeanInit

.Em /etc/rc
Secondary init script that is run if
.Em /etc/leaninit.d/rc
does not exist.

.Em /etc/leaninit.d/rc.conf
Provides config settings for
.Nm lrc(8)
and
.Nm LeanInit
scripts

.Em /etc/leaninit.d/rc.svc
Provides variables and functions for
.Nm LeanInit
scripts

.Em /etc/leaninit.d/rc.shutdown
Stops all processes and unmounts
all file systems before reboot.

.Em /etc/leaninit.d/svc.d
Folder containing scripts for starting various services (such as D-BUS).

.Em /etc/leaninit.d/svc.e
Location of all files used to determine which services are enabled.

.Em /var/log/leaninit/leaninit.log
Default log file for
.Nm LeanInit,
used by
.Nm rc.svc(8).

.Em /var/run/leaninit
Default location for LeanInit's .status and PID files
.Sh SEE ALSO
lhalt(8), lrc(8), lrc.conf(5), lrc.shutdown(8), lservice(8), rc.svc(8), rungetty(8), lttys(5)
.Sh AUTHOR
Johnothan King
