.\" Copyright (c) 2018-2019 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd July 22, 2019
.Dt LEANINIT-SERVICE 8
.Os
.Sh NAME
.Nm leaninit-service
.Nd service manager for
.Nm LeanInit
.Sh SYNOPSIS
.Nm leaninit-service service-name action [silent|verbose]
.Nm leaninit-service --status-all
.Sh DESCRIPTION
.Nm LeanInit's
service utility can do the following actions:

.Nm start
Starts a service if it is not currently started.

.Nm stop
Stops a service by issuing it SIGCONT and SIGTERM, then after seven seconds issuing it SIGKILL (only applies to services with active daemons).

.Nm restart
Restart a service, or start one if it isn't running.

.Nm try-restart
Restart a service if it is currently running, otherwise return an error.

.Nm enable
Enable a service by creating a file for it in /var/lib/leaninit/svc.
Equivalent to 'touch /var/lib/leaninit/svc/svcname'.

.Nm disable
Disable a service by removing its file in /var/lib/leaninit/svc.
Equivalent to 'rm /var/lib/leaninit/svc/svcname'.

.Nm force-reload
This will reload services that support reloading and restart services that do not support reloading.

.Nm reload
Reload a service without restarting it (the service must support reloading for this to work).

.Nm info
Sends the SIGINFO signal to the service's process when applicable.
This action is only available on FreeBSD.

.Nm pause
Sends the SIGSTOP signal to the service's process when applicable to pause it, then sets the service's status to 'Paused'.

.Nm cont
Sends the SIGCONT signal to the service's process when applicable to unpause it, then sets the service's status to 'Continued'.

.Nm status
Shows the status of a currently running service.
Equivalent to 'cat /var/run/leaninit/svcname.status'.

.Nm help
Displays usage information for the service itself.

.Nm --status-all
Shows the current statuses of all
.Nm LeanInit
services.

.Pp
In addition, services will accept an optional second argument that determines if the service has output.
This is used in
.Nm leaninit-rc(8)
to enable silent boot.

.Nm silent
Disables verbose output when running the service.

.Nm verbose
Enables verbose output when running the service (default).

.Sh EXAMPLES
Enable SSH:
service sshd enable

Show the current status of ntpd:
service ntpd status

Restart the X Server:
service xdm restart
.Sh SEE ALSO
leaninit-rc(8), leaninit-rc.svc(8)
.Sh AUTHOR
Johnothan King
