.\" Copyright (c) 2018 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd December 12, 2018
.Dt LGETTY 8
.Os
.Sh NAME
.Nm lgetty
.Nd a small getty program made for LeanInit
.Sh SYNOPSIS
.Nm lgetty tty [debug] ...
.Sh DESCRIPTION
.Nm LGetty
is a getty program for
.Nm LeanInit
that will launch
.Nm login(1)
on the specified tty with job control, and respawn
.Nm login(1)
when it ends.
Passing 'debug' as a second argument will cause
.Nm LGetty
to pass -p to
.Nm login(1),
which avoids overwritting existing environment variables such as
.Em $RUNLEVEL.

.Sh EXAMPLES
Launch
.Nm LGetty
on /dev/tty8:
lgetty /dev/tty8

Launch
.Nm LGetty
on /dev/ttyv4 as a seperate process:
lgetty /dev/ttyv4 &

.Sh SEE ALSO
login(1), lttys(5)
.Sh AUTHOR
Johnothan King
