.\" Copyright (c) 2018 Johnothan King. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in all
.\" copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.\" SOFTWARE.
.\"
.Dd October 24, 2018
.Dt RC 8
.Os
.Sh NAME
.Nm rc
.Nd init script
.Sh DESCRIPTION
The
.Nm rc
script is responsible for mounting all file systems and starting all services in
.Em /etc/leaninit.d/svc.e
concurrently.
If either
.Em /etc/rc.local
or
.Em /etc/leaninit.d/rc.local
exist and are executable,
.Nm rc
will run them after it launches all services.
.Pp
.Nm RC
will log the output from booting the system to
.Em /var/log/leaninit.log
by default.
.Sh FILES
.Em /etc/rc.local
Optional script run by
.Nm rc
if it exists.

.Em /etc/leaninit.d/rc.svc
Provides variables and functions to
.Nm rc

.Em /etc/leaninit.d/rc.conf
Config file for
.Nm rc
and
.Nm LeanInit
services

.Em /var/log/leaninit/leaninit.log
Default log file for
.Nm LeanInit
.Sh SEE ALSO
rc.conf(5), rc.svc(8)
.Sh AUTHOR
Johnothan King
