#!/bin/sh
. /etc/leaninit.d/rc.svc

# Service for ConsoleKit
NAME="ConsoleKit"
DAEMON=console-kit-daemon

main() {
	# D-Bus is required to run ConsoleKit
	waitforinit dbus dbus-daemon $1
	console-kit-daemon
}

run consolekit $1 $2
