#!/bin/sh
. /etc/leaninit.d/rc.svc

# elogind
NAME="elogind"
DAEMON=elogind-daemon

main() {
	waitforinit dbus dbus-daemon
	sleep 0.5
	/usr/libexec/elogind/elogind --daemon
	until [ "$(pgrep -x elogind-daemon)" != ""]; do
		false
	done
	/usr/libexec/elogind/elogind-uaccess-command /dev
}

run elogind $1 $2
