#!/bin/sh
. /etc/leaninit.d/rc.svc

# elogind
NAME="elogind"
TYPE=login-daemon
if [ -n "$(pgrep -x elogind-daemon)" ]; then
	DAEMON=elogind-daemon
else
	DAEMON=elogind
fi

main() {
	waitfor dbus
	if [ -n "$(command -v elogind)" ]; then
		elogind &
	elif [ -x /usr/libexec/elogind/elogind ]; then
		/usr/libexec/elogind/elogind &
	else
		print "Could not start elogind..." log ${RED}
		exit 1
	fi
	if [ -x /usr/libexec/elogind/elogind-uaccess-command ]; then
		/usr/libexec/elogind/elogind-uaccess-command /dev
		for fs in $(df -t tmpfs | tail -n +2 | awk '{print $6}'); do
			/usr/libexec/elogind/elogind-uaccess-command $fs
		done
	fi
}

run elogind $1 $2
