#!/bin/sh
. /etc/leaninit.d/rc.svc

# elogind
NAME="elogind"
TYPE=login-daemon
TARGET=Linux
if [ -n "$(pgrep -x elogind-daemon)" ]; then
	DAEMON=elogind-daemon
else
	DAEMON=elogind
fi

main() {
	waitfor service dbus
	if [ -n "$(command -v elogind)" ]; then
		elogind -D
	elif [ -x /usr/libexec/elogind/elogind ]; then
		/usr/libexec/elogind/elogind -D
	elif [ -x /usr/lib/elogind/elogind ]; then
		/usr/lib/elogind/elogind -D
	else
		return 1
	fi
	waitfor process $DAEMON return
	if [ -x /usr/libexec/elogind/elogind-uaccess-command ]; then
		/usr/libexec/elogind/elogind-uaccess-command /dev
		for fs in $(df -t tmpfs | tail -n +2 | awk '{print $6}'); do
			/usr/libexec/elogind/elogind-uaccess-command $fs
		done
	elif [ -x /usr/lib/elogind/elogind-uaccess-command ]; then
		/usr/lib/elogind/elogind-uaccess-command /dev
		for fs in $(df -t tmpfs | tail -n +2 | awk '{print $6}'); do
			/usr/lib/elogind/elogind-uaccess-command $fs
		done
	fi
}

run elogind "$@"
