#!/bin/sh
. /etc/leaninit.d/rc.svc

# Linux NetworkManager
NAME="NetworkManager"
DAEMON=NetworkManager
TYPE=networking
TARGET=Linux

main() {
	waitfor service dbus
	NetworkManager
}

run NetworkManager "$@"
