#!/bin/sh
. /etc/leaninit.d/rc.svc

# Network Time Protocol Daemon
NAME="ntpd"
DAEMON=ntpd

main() {
	# Wait for internet services to start
	waitforinit wpa_supplicant wpa_supplicant /var/run/leaninit/wpa.pid
	waitforinit dhcpcd dhcpcd
	ntpd
}

run ntpd $1 $2
