#!/bin/sh
. /etc/leaninit.d/rc.svc

# Network Time Protocol Daemon
NAME="ntpd"
DAEMON=ntpd

main() {
	# Wait for internet services to start
	waitforinit wpa_supplicant wpa_supplicant "$1" /var/run/leaninit/wpa.pid
	waitforinit dhcpcd dhcpcd $1
	ntpd
}

run ntpd $1 $2
