#!/bin/sh
. /etc/leaninit.d/rc.svc

# Launch gettys
NAME="Rungetty"
DAEMON=rungetty
TYPE=getty

# Open gettys on the ttys specified in /etc/leaninit.d/ttys
main() {
	GETTY=$(grep getty /etc/leaninit.d/ttys | grep -v '#')
	for tty in $(grep -Ev '#|getty' /etc/leaninit.d/ttys); do
		rungetty "/dev/$tty" "$GETTY $GETTYMODE $tty" &
	done
}

# Output an informative message to the user about LeanInit gettys
disable() {
	print "If you do not want the next execution of LeanInit's 'make install' to re-enable $NAME, run 'echo init > /etc/leaninit.d/svc.e/getty.type' as root" nolog ${PURPLE} ${WHITE}
	print "To re-enable $NAME after executing the above command, run 'rm /etc/leaninit.d/svc.e/getty.type && lservice rungetty enable' as root" nolog ${PURPLE} ${WHITE}
}

run rungetty "$@"
