#!/bin/sh
. /etc/leaninit.d/rc.svc

# Secure SHell Daemon
NAME="SSH"
DAEMON=sshd

main() {
	# Wait for internet services
	waitforinit wpa_supplicant wpa_supplicant /var/run/leaninit/wpa.pid
	waitforinit dhcpcd dhcpcd

	# sshd must be executed with the full path to the executable
	ssh-keygen -A >> /dev/null
	command $(command -v sshd)
}

run sshd $1 $2
