#!/bin/sh
. /etc/leaninit.d/rc.svc

# Linux NetworkManager
NAME="Wicd"
DAEMON=wicd
TYPE=networking
TARGET=Linux

main() {
	waitfor service dbus
	wicd
}

stop() {
	rm -f /var/run/wicd/wicd.pid
}

run wicd "$@"
