#!/bin/sh
. /etc/leaninit.d/rc.svc

# WPA Supplicant service (for FreeBSD)
NAME="WPA Supplicant"
DAEMON=wpa_supplicant
TYPE=networking
TARGET=FreeBSD

main() {
	waitfor process wpa_supplicant
	sleep 0.5
	pkill -KILL -x wpa_supplicant
	wpa_supplicant -s -B -D${NETDRIVER} -i${NETFACE} -c/etc/wpa_supplicant.conf -P /var/run/leaninit/wpa.pid
}

run wpa_supplicant "$@"
