#!/bin/sh
. /etc/leaninit.d/rc.svc

# Service for X Server Display Managers
NAME=$XDMNAME
DAEMON="$DM Xorg"

# The main function
main() {
	if [ "$DM" = "" ] || [ ! -x "$(command -v $DM)" ]; then
		echo 'The xdm service failed to start due to $DM being invalid!'
		return 1
	fi
	waitforinit dbus dbus-daemon
	fork "$DM"
}

run xdm $1 $2
