#!/bin/sh
. /etc/leaninit.d/rc.svc

# Service for X Server Display Managers
NAME=$XDMNAME
DAEMON=$DM

# The main function
main() {
	if [ ! -n "$DM" ] || [ ! -x "$(command -v $DM)" ]; then
		echo 'The xdm service failed to start due to $DM being invalid!'
		return 1
	fi
	install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix # Required for GDM to function
	dbus_req
	waitforinit consolekit console-kit-daemon
	waitforinit elogind elogind
	$DM &
}

# Kill the X server manually
stop() {
	pkill -x Xorg
	pkill -x $DM
}

run xdm $1 $2
