#!/bin/sh
#
# Copyright (c) 2017-2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source rc.api
. /etc/leaninit/rc.api

# Set the $GETTY variable
GETTY=`grep getty /etc/leaninit/ttys | sed '/#/d'`

# Check all the filesystems in /etc/fstab for damage, and repair them if needed
echo "Checking all filesystems for data corruption..."
DEFLINUX
fsck -A
ENDEF

DEFBSD
fsck -F
ENDEF

# Mount drives and datasets
echo "Remounting root as read-write..."
if [ "$ZFS_ENABLE" = "true" ]; then
	# Mount everything
	zfs mount -a

	# ZFS NFS
	zfs share -a

	# Turn on writes
	for z in `zpool list -H | awk '{print $1;}'`; do
		echo "Turning readonly off for dataset $z"
		zfs readonly=off $z
	done
else
	mount -o remount,rw /
fi
mount -a
swapon -a

# Remove the nologin file (if there is one)
rm -f /var/run/nologin

# Logging
touch $LOGFILE
mv $LOGFILE $LOGFILE.old
echo "LeanInit is running on `uname -srm`" > $LOGFILE

# sysctl(8)
print "Loading settings with sysctl..."
DEFLINUX
sysctl --system
ENDEF

DEFBSD
sysctl -f /etc/sysctl.conf
ENDEF

DEFLINUX
# Launch eudev (Linux)
print "Starting udev..."
udevd --daemon
udevadm trigger --type=devices
udevadm trigger --type=subsystems
udevadm settle
ENDEF

DEFBSD
# Launch devd (FreeBSD)
print "Starting devd..."
devd
devd -n

# Kill bad daemons
kill -s SIGKILL `psawk moused` || true
kill -s SIGKILL `psawk wpa_supplicant` || true
ENDEF

DEFLINUX
# Set up network interfaces
print "Setting up a loopback interface..."
ip link set up lo
print "Setting up $INTERFACE for networking..."
ip link set up $INTERFACE

# Load all modules specified in /etc/modules-load.d
if [ -d /etc/modules-load.d ]; then
	print "Loading kernel modules..."
	for m in `cat /etc/modules-load.d/* | sed '/#/d'`; do
		modprobe $m
	done
fi
ENDEF

# Set the hostname
if [ "$HOSTNAME" != "" ]; then
	print "Setting the hostname to $HOSTNAME..."
	fork "hostname $HOSTNAME"
fi

DEFLINUX
# Set the keyboard layout (this requires kbd to work)
if [ "$KEYMAP" != "" ]; then
	print "Setting the keyboard layout to $KEYMAP..."
	fork "loadkeys $KEYMAP"
fi
ENDEF

# Start the services
for sv in `ls /etc/leaninit/svce`; do
	fork "/etc/leaninit/svc-start $sv init"
done

# Open gettys on the ttys specified in /etc/leaninit/ttys
print "Launching gettys specified in /etc/leaninit/ttys..."
for tty in `cat /etc/leaninit/ttys | sed '/#/d' | sed '/getty/d'`; do
	fork "while true; do $GETTY $GETTYMODE $tty; done"
done

exit 0
