#!/bin/sh
#
# Copyright (c) 2017-2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source rc.svc
. /etc/leaninit.d/rc.svc

# Set the $GETTY variable
GETTY=$(grep getty /etc/leaninit.d/ttys | grep -v '#')

# Check all the file systems in /etc/fstab for damage, and repair them if needed
print "Checking all file systems for data corruption..." nolog ${LIGHT_PURPLE} ${WHITE}
DEFBSD
fsck -F
ENDEF
DEFLINUX
fsck -A

# Mount all drives
print "Mounting all drives..." nolog ${LIGHT_PURPLE} ${WHITE}
mount -a
mount -o remount,rw / 2> /dev/null || true

# Mount pseudo file systems
print "Mounting pseudo file systems..." nolog ${LIGHT_PURPLE} ${WHITE}
rm -rf /tmp/*
mkdir -p /run/shm /dev/pts
grep -q ' /dev '                 /etc/mtab || mount -o nosuid -t udev devtmpfs /dev
grep -q ' /dev/pts '             /etc/mtab || mount -o noexec,nosuid,gid=5,mode=0620 -t devpts devpts /dev/pts
grep -q ' /run '                 /etc/mtab || mount -o noexec,nosuid -t tmpfs tmpfs /run
grep -q ' /run/shm '             /etc/mtab || mount -o noexec,nosuid,mode=1777 -t tmpfs tmpfs /run/shm
grep -q ' /proc '                /etc/mtab || mount -o noexec,nosuid,nodev -t proc proc /proc
grep -q ' /sys '                 /etc/mtab || mount -o noexec,nosuid,nodev -t sysfs sysfs /sys
grep -q ' /sys/kernel/security ' /etc/mtab || mount -t securityfs securityfs /sys/kernel/security
grep -q ' /sys/fs/pstore '       /etc/mtab || mount -t pstore pstore /sys/fs/pstore
grep -q ' /sys/fs/cgroup '       /etc/mtab || mount -t tmpfs cgroup /sys/fs/cgroup
grep -q ' /tmp '                 /etc/mtab || mount -o noatime,noexec,nosuid,nodev,mode=1777 -t tmpfs tmpfs /tmp

# Launch either udev or mdev
if [ "$DEV" = "udev" ]; then
	print "Starting udev..." log ${BLUE} ${WHITE}
	$DEVEXEC --daemon
	udevadm trigger --type=devices
	udevadm trigger --type=subsystems
	udevadm settle
elif [ "$DEV" = "mdev" ]; then
	$DEVEXEC -s
fi

# Load all modules specified in /etc/modules-load.d and by `kmod static-nodes`
if [ -d /etc/modules-load.d ] && [ "$(ls /etc/modules-load.d)" != "" ]; then
	print "Loading kernel modules..." nolog ${LIGHT_PURPLE} ${WHITE}
	modprobe -a $(kmod static-nodes | awk '/Module:/ {print $2}') $(cat /etc/modules-load.d/* | grep -v '#')
fi
ENDEF

# Mount all ZFS file systems
if [ "$ZFS_ENABLE" = "true" ]; then
	print "Mounting all ZFS file systems..." nolog ${LIGHT_PURPLE} ${WHITE}

	# Done for compatibility with beadm(1)
	for z in "$(df -t zfs | tail -n +2 | awk '{print $1}')"; do
		zfs mount $z
	done

	# mount -a equivalent
	zfs mount -a

	# ZFS NFS
	zfs share -a

	# Turn on writes
	for z in $(zpool list -Ho name); do
		print "Turning readonly off for dataset $z" nolog ${LIGHT_PURPLE} ${WHITE}
		zfs readonly=off $z
	done
fi

# Swap
print "Turning on all swap partitions..." nolog ${LIGHT_PURPLE} ${WHITE}
swapon -a

# Logging
touch $LOGFILE $LOGFILE.2 $LOGFILE.3
mv $LOGFILE $LOGFILE.old
mv $LOGFILE.2 $LOGFILE.old.2
mv $LOGFILE.3 $LOGFILE.old.3
echo "LeanInit is running on $(uname -srm)" > $LOGFILE

# sysctl(8)
print "Launching sysctl(8)..." log ${BLUE} ${WHITE}
DEFLINUX
sysctl --system
sysctl fs.protected_hardlinks=1 # This should always be set to 1
sysctl fs.protected_symlinks=1
ENDEF

DEFBSD
for s in /etc/sysctl.conf /etc/sysctl.conf.local; do
	if [ -r $s ]; then
		sysctl -f /etc/sysctl.conf
	fi
done
ENDEF

# Remove the nologin and .status files
print "Removing any existing nologin files..." nolog ${LIGHT_PURPLE} ${WHITE}
rm -f /etc/nologin /run/nologin /var/run/nologin
print "Resetting /var/run/leaninit" nolog ${LIGHT_PURPLE} ${WHITE}
rm -rf /var/run/leaninit
mkdir -p /var/run/leaninit

DEFBSD
# Launch devd (vidcontrol -m is required for moused to function)
print "Starting devd..." log ${BLUE} ${WHITE}
vidcontrol -m on
fork "devd"
ENDEF

DEFLINUX
# Set up network interfaces
print "Setting up a loopback interface..." log ${BLUE} ${WHITE}
ip link set up dev lo
if [ "$INTERFACE" != "" ]; then
	for n in "$INTERFACE"; do
		print "Setting up $n for networking..." log ${BLUE} ${WHITE}
		ip link set up dev $n
	done
fi
ENDEF

# Set the hostname
if [ "$HOSTNAME" != "" ]; then
	print "Setting the hostname to $HOSTNAME..." nolog ${LIGHT_PURPLE} ${WHITE}
	fork "hostname $HOSTNAME"
fi

# Set the timezone
if [ "$TIMEZONE" != "" ] && [ -r /usr/share/zoneinfo/$TIMEZONE ]; then
	print "Setting the timezone to $TIMEZONE..." nolog ${LIGHT_PURPLE} ${WHITE}
	ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
fi

DEFLINUX
# Set the keyboard layout (this requires kbd to work)
if [ "$KEYMAP" != "" ]; then
	print "Setting the keyboard layout to $KEYMAP..." log ${BLUE} ${WHITE}
	fork "loadkeys $KEYMAP"
fi
ENDEF

# D-Bus support
if [ "$DBUS_ENABLE" = "true" ]; then
	mkdir -p /run/dbus
	rm -f /var/run/dbus/pid
	print "Starting D-Bus..." log ${BLUE} ${WHITE}
	dbus-daemon --system
	until [ "$(pgrep -x dbus-daemon)" != "" ]; do
		sleep 7
		print "Failed to start D-Bus..." log ${RED} ${LIGHT_RED}
		echo "Failure" > /var/run/leaninit/dbus.status
		break
	done
fi

# If there are no services enabled, go to finish()
if [ "$(ls /etc/leaninit.d/svc.e)" = "" ]; then
	finish
fi

# Start the services
for sv in $(ls /etc/leaninit.d/svc.e); do
	fork "INIT=true /etc/leaninit.d/svc.d/$sv start"
done

# Open gettys on the ttys specified in /etc/leaninit.d/ttys
print "Launching gettys on all ttys specified in /etc/leaninit.d/ttys..." log ${BLUE} ${WHITE}
for tty in $(grep -Ev '#|getty' /etc/leaninit.d/ttys); do
	fork "while true; do $GETTY $GETTYMODE $tty; done"
done

# Return to init
exit 0
