#!/bin/sh
#
# Copyright (c) 2017-2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Source rc.api
. /etc/leaninit/rc.api

# Set the $GETTY variable
GETTY=`grep getty /etc/leaninit/ttys | sed '/#/d'`

# Check all the filesystems in /etc/fstab for damage, and repair them if needed
print "Checking all filesystems for data corruption..." nolog ${LIGHT_PURPLE} ${WHITE}
DEFLINUX
fsck -A
ENDEF

DEFBSD
fsck -F
ENDEF

# Mount drives and datasets
print "Mounting all drives..." nolog ${LIGHT_PURPLE} ${WHITE}
mount -a
if [ "$ZFS_ENABLE" = "true" ]; then
	# Mount everything
	zfs mount -a

	# ZFS NFS
	zfs share -a

	# Turn on writes
	for z in `zpool list -Ho name`; do
		print "Turning readonly off for dataset $z" nolog ${LIGHT_PURPLE} ${WHITE}
		zfs readonly=off $z
	done
fi
mount -o remount,rw / 2> /dev/null || true
print "Turning on all swap partitions..." nolog ${LIGHT_PURPLE} ${WHITE}
swapon -a

# Remove the nologin file (if there is one)
print "Removing any existing nologin files..." nolog ${LIGHT_PURPLE} ${WHITE}
rm -f /run/nologin /var/run/nologin

# Logging
touch $LOGFILE
mv $LOGFILE $LOGFILE.old
echo "LeanInit is running on `uname -srm`" > $LOGFILE

# sysctl(8)
print "Launching sysctl(8)..." log ${LIGHT_BLUE} ${WHITE}
DEFLINUX
sysctl --system
ENDEF

DEFBSD
sysctl -f /etc/sysctl.conf
ENDEF

DEFLINUX
# Launch eudev (required for the X server to function)
print "Starting udev..." log ${LIGHT_BLUE} ${WHITE}
udevd --daemon
udevadm trigger --type=devices
udevadm trigger --type=subsystems
udevadm settle
ENDEF

DEFBSD
# Launch devd (vidcontrol -m is required for moused to function)
print "Starting devd..." log ${LIGHT_BLUE} ${WHITE}
vidcontrol -m on
fork "devd"
ENDEF

DEFLINUX
# Set up network interfaces
print "Setting up a loopback interface..." log ${LIGHT_BLUE} ${WHITE}
ip link set up lo
print "Setting up $INTERFACE for networking..." log ${LIGHT_BLUE} ${WHITE}
ip link set up $INTERFACE

# Load all modules specified in /etc/modules-load.d
if [ -d /etc/modules-load.d ]; then
	print "Loading kernel modules..." log ${LIGHT_BLUE} ${WHITE}
	for m in `cat /etc/modules-load.d/* | sed '/#/d'`; do
		modprobe $m
	done
fi
ENDEF

# Set the hostname
if [ "$HOSTNAME" != "" ]; then
	print "Setting the hostname to $HOSTNAME..." log ${LIGHT_BLUE} ${WHITE}
	fork "hostname $HOSTNAME"
fi

DEFLINUX
# Set the keyboard layout (this requires kbd to work)
if [ "$KEYMAP" != "" ]; then
	print "Setting the keyboard layout to $KEYMAP..." log ${LIGHT_BLUE} ${WHITE}
	fork "loadkeys $KEYMAP"
fi
ENDEF

# Start the services
for sv in `ls /etc/leaninit/svce`; do
	fork "/etc/leaninit/svc-start $sv init"
done

# Open gettys on the ttys specified in /etc/leaninit/ttys
print "Launching gettys on all ttys specified in /etc/leaninit/ttys..." log ${LIGHT_BLUE} ${WHITE}
for tty in `cat /etc/leaninit/ttys | sed '/#/d' | sed '/getty/d'`; do
	fork "while true; do $GETTY $GETTYMODE $tty; done"
done

exit 0
