#!/bin/sh
#
# Copyright (c) 2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# svc-stop - used internally by rc and lsvc to stop services
#

# Source rc.api
. /etc/leaninit/rc.api

# Only allow root to run this, with proper arguments
if [ $(id -u) != 0 ] || [ "$1" = "" ]; then
	print "This script is only meant for internal use!" nolog ${RED} ${LIGHT_RED}
	exit 1
fi

# Source the service's script
. /etc/leaninit/svc/$1

# Do not attempt to run if the service is not running
if [ "$(psnoawk $DAEMON)" = "" ]; then
	print "$NAME is not running" nolog ${LIGHT_PURPLE} ${YELLOW}
	exit 0
fi

# Stop $NAME
print "Stopping $NAME..." log ${BLUE} ${WHITE}
kill $(psawk $DAEMON)

# Exit with error if the service failed to stop
RET=$?
if [ $? != 0 ] && [ "$2" != "f" ]; then
	print "$NAME failed to stop (kill exited with status $RET)" log ${RED} ${LIGHT_RED}
	exit $RET
fi

# Send SIGKILL if SIGTERM did not work (force only)
print "Sending $NAME SIGKILL..." log ${BLUE} ${LIGHT_GRAY}
kill -s SIGKILL $(psawk $DAEMON)

# Finish
if [ "$(psnoawk $DAEMON)" != "" ]; then
	print "$NAME failed to stop (did not respond to SIGKILL, may be a zombie process)" log ${RED} ${LIGHT_RED}
	echo "Zombie" > /var/log/leaninit/$1.status
	exit 1
else
	print "Stopped $NAME successfully" log ${LIGHT_GREEN} ${WHITE}
	rm -f /var/log/leaninit/$1.status
	exit 0
fi
