#!/bin/sh

# WPA Supplicant service (for FreeBSD)
NAME="WPA Supplicant"
TYPE=networking
TARGET=FreeBSD

main() {
	waitfor process wpa_supplicant
	sleep 0.5
	pkill -KILL -x wpa_supplicant
	wpa_supplicant -s -B -D${NETDRIVER} -i${NETFACE} -c/etc/wpa_supplicant.conf -P "$__svcpidfile"
}

restart() {
	wpa_supplicant -s -B -D${NETDRIVER} -i${NETFACE} -c/etc/wpa_supplicant.conf -P "$__svcpidfile"
}

. /etc/leaninit/rc.svc
