#!/bin/sh
NAME="Networking"
TYPE="networking"

# Setup networking on NetBSD
main() {
    # dhcpcd
    for n in $WIRED $WIRELESS; do
        fork dhcpcd -B $n
    done

    # wpa_supplicant
    if [ "$WIRED" ]; then
        for n in $WIRED; do
            fork wpa_supplicant -s -Dwired "-i$n" -c/etc/wpa_supplicant.conf
        done
    fi
    if [ "$WIRELESS" ]; then
        for n in $WIRELESS; do
            fork wpa_supplicant -s -Dbsd "-i$n" -c/etc/wpa_supplicant.conf
        done
    fi

    # Give the networking time to start
    sleep 2
}

. /etc/leaninit/rc.svc
