#!/bin/sh
NAME="WPA Supplicant"
TYPE="networking"

# Run wpa_supplicant on all interfaces
main()
{
    if [ "$WIRED" ]; then
        for n in $WIRED; do
            fork wpa_supplicant -s -Dwired "-i$n" -c/etc/wpa_supplicant.conf
        done
    fi
    if [ "$WIRELESS" ]; then
        for n in $WIRELESS; do
            fork wpa_supplicant -s -Dbsd "-i$n" -c/etc/wpa_supplicant.conf
        done
    fi
}

. /etc/leaninit/rc.svc
