#!/bin/sh

# Service for X Server Display Managers
NAME="X Display Manager"
TYPE="display-manager"

# The main function
main()
{
    waitfor service settings
    install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix
    fork "$XDM" -nodaemon -config /etc/X11/xdm/xdm-config
}

# Kill the X server manually
stop()
{
    rm -f /var/run/leaninit/xdm* "/var/run/leaninit/$TYPE.type"
    pkill -x xdm
    pkill -x Xorg
}

. /etc/leaninit/rc.svc
