#!/bin/sh

# Service for X Server Display Managers
NAME="X Display Manager"
TYPE="display-manager"
__svcname=$(basename "$0")

main() {
    waitfor service settings
    install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix
    /usr/X11R7/bin/xdm -config /etc/X11/xdm/xdm-config
    ln -s /var/run/xdm.pid "$__svcpidfile"
}

# Reload functionality
reload() {
    kill -HUP $__svcpid
}

# Kill the X server manually
stop() {
    rm -f /var/run/leaninit/xdm* "/var/run/leaninit/$TYPE.type"
    pkill -x xdm
    pkill -x Xorg
}

. /etc/leaninit/rc.svc
