#!/bin/sh
. /etc/leaninit/rc.svc

# Service for acpid (either BusyBox or other implementation)
NAME="ACPI Daemon"
TARGET=Linux

main() {
	waitfor service dbus optional
	acpid -p "$__svcpidfile"
}

run "$@"
