#!/bin/sh
. /etc/leaninit/rc.svc

# Service for apache httpd
NAME="Apache Web Server"

main() {
	mkdir -p /run/httpd /var/run/httpd
	fork httpd -k start -DFOREGROUND
}

stop() {
	httpd -k graceful-stop
}

reload() {
	pkill -HUP -x httpd
}

run "$@"
