#!/bin/sh
. /etc/leaninit.d/rc.svc

# Service for ConsoleKit
NAME="ConsoleKit"
TYPE=login-daemon

main() {
	waitfor service dbus
	console-kit-daemon --no-daemon &
	jobs -p %+ > /var/run/leaninit/consolekit.pid
}

run "$@"
