#!/bin/sh
. /etc/leaninit.d/rc.svc

# dhcpcd (for Linux)
NAME="dhcpcd"
TYPE=networking

main() {
	for n in $NETFACE; do
		dhcpcd -B $n &
		echo " $(jobs -p %+)" >> /var/run/leaninit/dhcpcd.pid
	done
}

run "$@"
