#!/bin/sh
. /etc/leaninit/rc.svc

# elogind
NAME="elogind"
TYPE=login-daemon
TARGET=Linux

main() {
	waitfor service dbus
	if [ -n "$(command -v elogind)" ]; then
		elogind &
	elif [ -x /usr/libexec/elogind/elogind ]; then
		/usr/libexec/elogind/elogind &
	elif [ -x /usr/lib/elogind/elogind ]; then
		/usr/lib/elogind/elogind &
	else
		print "Could not find the elogind binary!" log "$RED"
		return 1
	fi
	jobs -p %+ > "$__svcpidfile"
	if [ -x /usr/libexec/elogind/elogind-uaccess-command ]; then
		EUACCESS=/usr/libexec/elogind/elogind-uaccess-command
	elif [ -x /usr/lib/elogind/elogind-uaccess-command ]; then
		EUACCESS=/usr/lib/elogind/elogind-uaccess-command
	fi
	if [ -n "$EUACCESS" ]; then
		for fs in /dev $(df -t tmpfs | tail -n +2 | awk '{print $6}'); do
			"$EUACCESS" $fs
		done
	fi
}

run "$@"
