#!/bin/sh
. /etc/leaninit.d/rc.svc

# Launch gettys
NAME="LGetty"
TYPE=getty

# Open gettys on the ttys specified in /etc/leaninit.d/ttys
main() {
	for tty in $(grep -v '#' /etc/leaninit.d/ttys); do
		lgetty "/dev/$tty" &
		echo " $(jobs -p %+)" >> /var/run/leaninit/lgetty.pid
	done
}

# Output an message to the user about disabling LGetty
disable() {
	print "If you do not want the next execution of LeanInit's 'make install' to re-enable $NAME when no other getty type services are enabled," nolog ${PURPLE} ${WHITE}
	print "run 'echo init > /etc/leaninit.d/svc.e/getty.type' as root" nolog ${PURPLE} ${WHITE}
	print "To re-enable $NAME after executing the above command, run 'rm /etc/leaninit.d/svc.e/getty.type && lservice lgetty enable' as root" nolog ${PURPLE} ${WHITE}
}

run "$@"
