#!/bin/sh
. /etc/leaninit/rc.svc

# Samba
NAME="Samba"

# Main function
main() {
	waitfor networking
	smbd -F &
	jobs -p %+ > /var/run/leaninit/samba.pid
}

reload() {
	pkill -HUP -x smbd
}

run "$@"
