#!/bin/sh
NAME="LeanInit Logger"

main()
{
	# Start logging
	waitfor service zfs optional
	touch "$LOGFILE"
	mv "$LOGFILE" "$LOGFILE.old"
	echo "LeanInit has started logging on $(uname -srm)" > "$LOGFILE"

	# Remove nologin and /var/run/leaninit
	print "Removing any existing nologin files and resetting /var/run/leaninit..." log "$BLUE" "$WHITE"
	rm -rf /etc/nologin /run/nologin /var/run/nologin /var/run/leaninit
	mkdir -p /var/run/leaninit
}

. /etc/leaninit/rc.svc
