#!/bin/sh
NAME="Bluetooth daemon"
TYPE="bluetooth"
__svcname=$(basename "$0")

main() {
    waitfor service dbus
    if [ -x /usr/lib/bluetooth/bluetoothd ]; then
        fork /usr/lib/bluetooth/bluetoothd
    else
        fork bluetoothd
    fi
}

. /etc/leaninit/rc.svc
