#!/bin/sh
NAME="dhcpcd"
__svcname=$(basename "$0")

main() {
    waitfor networking
    for n in $(ip -o link show | awk '{ gsub(":", ""); print $2 }'); do
        fork dhcpcd -B $n
    done
}

. /etc/leaninit/rc.svc
