#!/bin/sh
NAME="elogind"
TYPE="login-daemon"

main()
{
	# elogind requires Cgroups and D-Bus
	waitfor service mountpfs
	waitfor service dbus

	# Run elogind
	if [ -n "$(command -v elogind)" ]; then
		elogind -D
	elif [ -x /usr/libexec/elogind/elogind ]; then
		/usr/libexec/elogind/elogind -D
	elif [ -x /usr/lib/elogind/elogind ]; then
		/usr/lib/elogind/elogind -D
	else
		print 'Could not find the elogind binary!' log "$RED"
		return 1
	fi

	# Symlink the elogind PID file to the correct location
	ln -s /var/run/elogind.pid "$__svcpidfile"

	# If elogind-uaccess-command exists, run it
	if [ -x /usr/libexec/elogind/elogind-uaccess-command ]; then
		EUACCESS=/usr/libexec/elogind/elogind-uaccess-command
	elif [ -x /usr/lib/elogind/elogind-uaccess-command ]; then
		EUACCESS=/usr/lib/elogind/elogind-uaccess-command
	fi
	if [ -n "$EUACCESS" ]; then
		for fs in /dev $(df -t tmpfs | tail -n +2 | awk '{print $6}'); do
			"$EUACCESS" "$fs"
		done
	fi
}

. /etc/leaninit/rc.svc
