#!/bin/sh
NAME="iNet Wireless Daemon"
__svcname=$(basename "$0")

main() {
    waitfor service netface
    waitfor service dbus
    waitfor networking optional
    fork /usr/lib/iwd/iwd
}

. /etc/leaninit/rc.svc
