#!/bin/sh
NAME="Kernel Modules"
MSG="Loading kernel modules"

main()
{
    if [ "$(ls /etc/modules-load.d 2> /dev/null)" ]; then
        modprobe -a $(cat /etc/modules-load.d/* | grep -v '#')
    else
        return 0
    fi
}

. /etc/leaninit/rc.svc
