#!/bin/sh
NAME="Linux-Specific Settings"
MSG="Setting up a loopback interface"

main()
{
	# Set up network interfaces
	ip link set up dev lo &
	if [ -n "$NETFACE" ]; then
		for n in $NETFACE; do
			print "Setting up $n for networking..." log "$BLUE" "$WHITE"
			ip link set up dev $n &
		done
	fi

	# Keyboard layout
	print "Setting the keyboard layout to $KEYMAP..." nolog "$PURPLE" "$WHITE"
	loadkeys "$KEYMAP" &
	wait
}

. /etc/leaninit/rc.svc
