#!/bin/sh
. /etc/leaninit/rc.conf.d/udev.conf
NAME="BusyBox mdev"
TYPE="udev"

main()
{
	echo $DEVEXEC > /proc/sys/kernel/hotplug # The kernel must be built with hotplug support for this to work
	$DEVEXEC -s
}

. /etc/leaninit/rc.svc
