#!/bin/sh
. /etc/leaninit/rc.conf.d/udev.conf
NAME="BusyBox mdev"
TYPE="udev"
__svcname=$(basename "$0")

main() {
    echo $DEVEXEC > /proc/sys/kernel/hotplug # The kernel must be built with hotplug support for this to work
    $DEVEXEC -s
    chmod 0666 /dev/stdout /dev/null
}

. /etc/leaninit/rc.svc
