#!/bin/sh
NAME="BusyBox mdev"
TYPE="udev"

main()
{
	"$DEVEXEC" -s
	echo "$DEVEXEC" > /proc/sys/kernel/hotplug # The kernel must be built with hotplug support for this to work
}

. /etc/leaninit/rc.svc
