#!/bin/sh
NAME="Pseudo File Systems"
MSG="Mounting secondary pseudo file systems"

# Mount pseudo file systems in parallel
main()
{
    # Make the required directories
    mkdir -p /dev/mqueue /dev/shm /dev/pts /run/shm /sys/fs/cgroup /sys/fs/pstore /sys/kernel/security

    # Mount the pseudo file systems
    mountpoint -q /dev/pts             || mount -o nosuid,noexec,noatime,gid=5,mode=0620 -t devpts devpts /dev/pts &
    mountpoint -q /dev/mqueue          || mount -o noatime -t mqueue none /dev/mqueue &
    mountpoint -q /sys/kernel/debug    || mount -o noatime -t debugfs none /sys/kernel/debug &  # The debugfs is essential for overclocking AMD GPUs
    mountpoint -q /sys/kernel/security || mount -o noatime -t securityfs securityfs /sys/kernel/security &
    mountpoint -q /sys/fs/pstore       || mount -o noatime -t pstore pstore /sys/fs/pstore &
    mountpoint -q /run/shm             || mount -n -o nosuid,nodev,mode=1777,noatime -t tmpfs tmpfs /run/shm
    mount --bind /run/shm /dev/shm &

    # Mount a tmpfs at /sys/fs/cgroup (Cgroups support)
    print "Mounting cgroups..." log "$BLUE" "$WHITE"
    mountpoint -q /sys/fs/cgroup || mount -o nosuid,nodev,noexec,noatime -t tmpfs cgroup /sys/fs/cgroup

    # elogind assumes the openrc cgroup is present (other cgroups, such as a 'leaninit' cgroup, don't work here)
    mkdir -p /sys/fs/cgroup/openrc /sys/fs/cgroup/unified
    mountpoint -q /sys/fs/cgroup/openrc || mount -o nosuid,nodev,noexec,noatime,name=openrc -t cgroup openrc /sys/fs/cgroup/openrc &

    # Support for Cgroups v2
    mountpoint -q /sys/fs/cgroup/unified || mount -o nosuid,nodev,noexec,noatime -t cgroup2 cgroup2 /sys/fs/cgroup/unified &

    # Wait for all jobs to finish
    wait
}

. /etc/leaninit/rc.svc
