#!/bin/sh
NAME="NetworkManager"
TYPE="networking"

main()
{
	waitfor service settings
	waitfor service dbus
	waitfor service iwd optional
	NetworkManager --pid-file="$__svcpidfile"
}

. /etc/leaninit/rc.svc
