#!/bin/sh
NAME="NetworkManager"
TYPE="networking"
__svcname=$(basename "$0")

main() {
    waitfor service netface
    waitfor service dbus
    NetworkManager --pid-file="$__svcpidfile"
}

. /etc/leaninit/rc.svc
