#!/bin/sh
. /etc/leaninit/rc.conf.d/udev.conf
NAME="udev"
TYPE="udev"

main() {
    "$DEVEXEC" --daemon
    udevadm info --cleanup-db
    udevadm trigger --action=add
    udevadm settle
}

reload() {
    udevadm control --reload-rules
    udevadm trigger
}

stop() {
    udevadm control --exit
}

. /etc/leaninit/rc.svc
