#!/bin/sh
NAME="Wicd"
TYPE="networking"
__svcname=$(basename "$0")

main() {
    waitfor service netface
    waitfor service dbus
    wicd
    ln -s /var/run/wicd/wicd.pid "$__svcpidfile"
}

# The PID file must be removed manually
stop() {
    rm -f /var/run/wicd/wicd.pid
}

. /etc/leaninit/rc.svc
