#!/bin/sh
. /etc/leaninit.d/rc.svc

# Avahi
NAME="Avahi"

main() {
	waitfor service dbus
	avahi-daemon &
	jobs -p %+ > /var/run/leaninit/avahi.pid
}

reload() {
	avahi-daemon --reload
}

run avahi "$@"
