#!/bin/sh
. /etc/leaninit.d/rc.svc

# D-Bus (required by many other services)
NAME="D-Bus"

# Launch D-Bus
main() {
	mkdir -p /run/dbus /var/run/dbus
	rm -f /run/dbus/pid /var/run/dbus/pid
	dbus-daemon --fork --system --print-pid > /var/run/leaninit/dbus.pid
	if [ ! -r /etc/machine-id ]; then
		dbus-uuidgen > /etc/machine-id
	fi
	waitfor process dbus-daemon return
}

# This causes D-Bus to partially reload
reload() {
	pkill -HUP -x dbus-daemon
}

run dbus "$@"
