#!/bin/sh
. /etc/leaninit.d/rc.svc

# Linux NetworkManager
NAME="NetworkManager"
TYPE=networking
TARGET=Linux

main() {
	waitfor service dbus
	NetworkManager --pid-file=/var/run/leaninit/NetworkManager.pid
}

run "$@"
