#!/bin/sh
. /etc/leaninit.d/rc.svc

# Secure SHell Daemon
NAME="SSH"

main() {
	# Wait for internet services
	waitfor networking

	# sshd must be executed with the full path to the executable
	ssh-keygen -A >> /dev/null
	command $(command -v sshd) -D &
	jobs -p %+ > /var/run/leaninit/sshd.pid
}

reload() {
	pkill -HUP -x sshd
}

run sshd "$@"
