#!/bin/sh
. /etc/leaninit.d/rc.svc

# Linux NetworkManager
NAME="Wicd"
TYPE=networking
TARGET=Linux

main() {
	waitfor service dbus
	wicd
	ln -s /var/run/wicd/wicd.pid /var/run/leaninit/wicd.pid
}

stop() {
	rm -f /var/run/wicd/wicd.pid
}

run wicd "$@"
