#!/bin/sh
. /etc/leaninit.d/rc.svc

# Service for X Server Display Managers
NAME=$XDMNAME
TYPE=display-manager

# The main function
main() {
	if [ ! -n "$DM" ] || [ ! -x "$(command -v $DM)" ]; then
		print 'The xdm service failed to start due to $DM being invalid!' log ${RED}
		return 1
	fi
	waitfor service dbus
	waitfor login-daemon optional
	install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix # Required for GDM to function
	$DM &
	jobs -p %+ > /var/run/leaninit/xdm.pid
}

# Kill the X server manually
stop() {
	pkill -x Xorg
}

run xdm "$@"
